server.port=9090
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Task 1 Exercise 1: Example route
spring.cloud.gateway.routes[0].id=example_route
spring.cloud.gateway.routes[0].uri=http://example.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**

# Task 1 Exercise 2: Load balanced route
spring.cloud.gateway.routes[1].id=load_balanced_route
spring.cloud.gateway.routes[1].uri=lb://example-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/loadbalanced/**

# Task 4 & Task 5: Greet service route
spring.cloud.gateway.routes[2].id=greet-service
spring.cloud.gateway.routes[2].uri=lb://greet-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/greet-service/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/greet-service/(?<segment>.*), /$\{segment}

# Bank Account & Loan routes
spring.cloud.gateway.routes[3].id=account-service
spring.cloud.gateway.routes[3].uri=lb://account-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/accounts/**

spring.cloud.gateway.routes[4].id=loan-service
spring.cloud.gateway.routes[4].uri=lb://loan-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/loans/**

# Task 1 Exercise 3: Resilience4j properties
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50
