<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.cognizant</groupId>
    <artifactId>microservices-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>microservices-parent</name>
    <description>Parent Aggregator POM for Spring Boot 3 &amp; Spring Cloud Microservices Suite</description>

    <modules>
        <module>account</module>
        <module>loan</module>
        <module>eureka-discovery-server</module>
        <module>greet-service</module>
        <module>api-gateway</module>
        <module>auth-service</module>
        <module>user-service</module>
        <module>order-service</module>
    </modules>
</project>
